config/routes.rb
Rails.application.routes.draw do

  get 'broken_smartphone/top'
  get 'broken_smartphone/talk_history_1', to: 'broken_smartphone#talk_history_1', as: 'broken_smartphone_talk_history_1'
  get 'broken_smartphone/talk_history_2', to: 'broken_smartphone#talk_history_2', as: 'broken_smartphone_talk_history_2'
  get 'broken_smartphone/hotograph_history_1', to: 'broken_smartphone#hotograph_history_1', as: 'broken_smartphone_hotograph_history_1'
  get 'broken_smartphone/memo_history_1', to: 'broken_smartphone#memo_history_1', as: 'broken_smartphone_memo_history_1'


  get 'line_page/top',    to: 'line_page#top',    as: 'line_page_top'
  get 'line_page/history',    to: 'line_page#history',    as: 'line_page_history'
  get 'line_page/group',  to: 'line_page#group',  as: 'line_page_group'
  post 'line_page/group', to: 'line_page#group'
  get 'line_page/hayato',  to: 'line_page#hayato', as: 'line_page_hayato'
  post 'line_page/hayato', to: 'line_page#hayato'
  get 'line_page/keisuke', to: 'line_page#keisuke',as: 'line_page_keisuke'
  post 'line_page/keisuke', to: 'line_page#keisuke'
  get 'line_page/child_consultation', to: 'line_page#child_consultation',as: 'line_page_child_consultation'
  post 'line_page/child_consultation', to: 'line_page#child_consultation'

  get 'google_page/top'
  get 'google_page/index', to: 'google_page#index', as: 'google_page_index'
  get 'google_page/page_1', to: 'google_page#page_1', as: 'google_page_page_1'
  get 'google_page/page_2', to: 'google_page#page_2', as: 'google_page_page_2'
  get 'google_page/page_3', to: 'google_page#page_3', as: 'google_page_page_3'
  get 'google_page/page_4', to: 'google_page#page_4', as: 'google_page_page_4'
  get 'google_page/page_5',  to: 'google_page#page_5',   as: 'google_page_page_5'
  get 'google_page/page_6',  to: 'google_page#page_6',   as: 'google_page_page_6'
  get 'google_page/page_7',  to: 'google_page#page_7',   as: 'google_page_page_7'
  get 'google_page/page_8',  to: 'google_page#page_8',   as: 'google_page_page_8'
  get 'google_page/page_9',  to: 'google_page#page_9',   as: 'google_page_page_9'
  get 'google_page/page_10', to: 'google_page#page_10',  as: 'google_page_page_10'
  get 'google_page/page_11', to: 'google_page#page_11',  as: 'google_page_page_11'

  get 'bakusai/top', to: 'bakusai#top', as: 'bakusai_top'
  get 'bakusai/page_1', to: 'bakusai#page_1', as: 'bakusai_page_1'
  get 'bakusai/page_2', to: 'bakusai#page_2', as: 'bakusai_page_2'
  get 'bakusai/page_3', to: 'bakusai#page_3', as: 'bakusai_page_3'
  get 'bakusai/page_4', to: 'bakusai#page_4', as: 'bakusai_page_4'
  get 'bakusai/page_5',  to: 'bakusai#page_5',   as: 'bakusai_page_5'
  get 'bakusai/page_6',  to: 'bakusai#page_6',   as: 'bakusai_page_6'
  get 'bakusai/page_7',  to: 'bakusai#page_7',   as: 'bakusai_page_7'
  get 'bakusai/page_8',  to: 'bakusai#page_8',   as: 'bakusai_page_8'
  get 'bakusai/page_9',  to: 'bakusai#page_9',   as: 'bakusai_page_9'
  get 'bakusai/page_10', to: 'bakusai#page_10',  as: 'bakusai_page_10'
  get 'bakusai/page_11', to: 'bakusai#page_11',  as: 'bakusai_page_11'

  root 'home#index'
  get 'home/dashboard', to: 'home#dashboard'


  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/line_page_controller.rb
class LinePageController < ApplicationController
  before_action :set_user, only: [:keisuke, :hayato, :group, :child_consultation]

  def top
    # トップページの処理が必要なら記述
  end

  def history

  end

  def child_consultation
    if request.get?
      # GETリクエスト時の処理があれば記述
    elsif request.post?
      case @user.progress_level
      when 12
        # 拡張性していく
        process_group_step(:chat_8, params[:chat_8], ->(input){ input.include?("室谷隼人") && input.include?("横山圭介") }, 13)
      when 13
        # 拡張性していく
        process_group_step(:chat_9, params[:chat_9], ->(input){ input.include?("別人") }, 14)
      else
        flash[:alert] = "無効な状態です"
      end
      redirect_to line_page_child_consultation_path and return
    end
  end


  # keisukeアクション
  # GETリクエスト時に進捗レベル0ならレベル1に更新
  # POSTリクエスト時はchat_1を更新（この例では検証処理はなし）
  def keisuke
    if request.get?
      if @user.progress_level == 0
        @user.update(progress_level: 1)
      end
    elsif request.post?
      if @user.progress_level == 1
        @user.keisuke.update(chat_1: params[:chat_1])
      elsif @user.progress_level == 13
        @user.keisuke.update(chat_2: params[:chat_2])
      end
      redirect_to line_page_keisuke_path and return
    end
  end

  # hayatoアクション
  # POSTリクエスト時に進捗レベル1の場合、chat_1を更新し検証後、進捗レベルを2に更新
  def hayato
    if request.post? && @user.progress_level == 1
      @user.hayato.update(chat_1: params[:chat_1])
      if valid_hayato?(@user.hayato.chat_1)
        @user.update(progress_level: 2)
      else
        flash[:alert] = "不正解です"
      end
      redirect_to line_page_hayato_path and return
    end
  end

  # groupアクション
  # 進捗レベルに応じた処理をcase文で分岐
  def group
    if request.get?
      # GETリクエスト時の処理があれば記述
    elsif request.post?
      case @user.progress_level
      when 2
        # 進捗レベル2：chat_1の入力検証（「米松」または「茉莉」を含むか）
        process_group_step(:chat_1, params[:chat_1], ->(input){ input.include?("米松") || input.include?("茉莉") }, 3)
      when 3
        # 進捗レベル3：chat_2の入力検証（"キャンペル"と一致するか）
        process_group_step(:chat_2, params[:chat_2], ->(input){ input == "キャンペル" }, 4)
      when 5
        # 進捗レベル5：chat_4の入力検証（例：期待する値と一致するか）
        process_group_step(:chat_3, params[:chat_3], ->(input){ input.include?("瀬戸ビル") }, 6)
      when 6
        # 進捗レベル6：chat_5の入力検証（例：正規表現で判定）
        process_group_step(:chat_4, params[:chat_4], ->(input){ input.include?("加納卓也") }, 7)
      when 7
        # 進捗レベル7：chat_6の入力検証（例：複数のキーワードを含むか）
        process_group_step(:chat_5, params[:chat_5], ->(input){ input.include?("川口会") }, 8)
      when 9
        # 進捗レベル8：chat_7の入力検証（例：特定の文字列で始まるか）
        process_group_step(:chat_6, params[:chat_6], ->(input){ input.include?("野崎山小学校") }, 10)
      when 10
        # 進捗レベル9：chat_8の入力検証（例：特定の文字列で終わるか）
        process_group_step(:chat_7, params[:chat_7], ->(input){ input.include?("喜一") }, 11)
      when 14
        # 拡張性していく
        process_group_step(:chat_10, params[:chat_10], ->(input){ input.include?("例のキーワード") }, 15)
      when 15
        # 拡張性していく
        process_group_step(:chat_11, params[:chat_11], ->(input){ input.include?("例のキーワード") }, 16)
      when 16
        # 拡張性していく
        process_group_step(:chat_12, params[:chat_12], ->(input){ input.include?("例のキーワード") }, 17)
      else
        flash[:alert] = "無効な状態です"
      end
      redirect_to line_page_group_path and return
    end
  end

  private

  # hayatoの入力検証用メソッド（「メール」または「写真」を含むかどうか）
  def valid_hayato?(input)
    input.include?("メール") || input.include?("写真")
  end

  # groupアクションの各ステップ処理を共通化するヘルパーメソッド
  # field: 更新対象の属性、value: パラメータ、validation_proc: 検証用Proc、next_level: 正解時に更新する進捗レベル
  def process_group_step(field, value, validation_proc, next_level)
    group = @user.line_group
    group.update(field => value)
    if validation_proc.call(group.send(field))
      @user.update(progress_level: next_level)
    else
      flash[:alert] = "不正解です"
    end
  end

  def set_user
    @user = current_user
  end
end

app/helpers/line_page_helper.rb
module LinePageHelper
end

app/views/line_page/child_consultation.html.erb
<div class="chat-container">
  <div class="chat-header">
    <div class="back-button">
      <%= link_to line_page_top_path do %>
        <span class="back-icon">&larr;</span> 戻る
      <% end %>
    </div>
    <div class="header-title">児童相談所</div>
  </div>

  <div class="chat-body">

    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend"><%= current_user.name %>様</br>
                                      ご連絡ありがとうございます。</br>
                                      詳細を確認をさせて頂くため</br>
                                      チャットで連絡いたしました。</div>
      </div>
    </div>

    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">米松喜一くんのネグレクトの件ですが</br>
                                      実は、先週も<%= current_user.name %>様以外の方からも</br>
                                      本件の相談の連絡がありました。</br>
                                      1件のみの通報だと立場上、動きにくく</div>
      </div>
    </div>

    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend"><%= current_user.name %>様の通報により</br>
                                      米松氏への指導に踏み切れるので、</br>
                                      心から感謝いたします。</br>
                                      </div>
      </div>
    </div>

    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">１点だけ確認させて頂きたいのですが</br>
                                      本件について把握している方は</br>
                                      <%= current_user.name %>様の他にいらっしゃいますか</br>
                                      よろしければ、全員をフルネームで</br>教えていただけますでしょうか。</div>
      </div>
    </div>


<% if current_user.line_group.chat_8.present? %>
<div class="message-container user">
<img src="https://upload.wikimedia.org/wikipedia/commons/4/41/LINE_logo.svg" alt="LINE" width="40">
<div class="message-content">
    <div class="username">自分</div>
    <div class="message user"><%= current_user.line_group.chat_8 %></div>
</div>
</div>
<% end %>
    
<% if current_user.progress_level >= 13 %>
    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">ありがとうございます。</br>
                                      室谷隼人様と横山圭介様ですね</br>
                                      </div>
      </div>
    </div>
    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">行政への報告書のため３名の名前を</br>
                                      記載させていただきます。</br>
                                      </div>
      </div>
    </div>
    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">実は、先週通報くれた方の名前が</br>
                                      米松圭介様という方でして、</br>
                                      その方とは連絡が取れない状態でして</br>
                                      横山圭介様の旧姓が米松であるなど</br>
                                      聞いたことは無いでしょうか</div>
      </div>
    </div>

    <% if current_user.line_group.chat_9.present? %>
    <div class="message-container user">
    <img src="https://upload.wikimedia.org/wikipedia/commons/4/41/LINE_logo.svg" alt="LINE" width="40">
    <div class="message-content">
        <div class="username">自分</div>
        <div class="message user"><%= current_user.line_group.chat_9 %></div>
    </div>
    </div>
    <% end %>
<% end %>


<% if current_user.progress_level >= 14 %>
    <div class="message-container friend">
      <img src="/assets/zidousoudann.png" alt="Instagram" width="40">
      <div class="message-content">
          <div class="username">児童相談所</div>
          <div class="message friend">かしこまりました。</br>
                                      ご友人様に対し失礼な質問を</br>お聞きし申し訳ございません。</br>
                                      引き続き、</br>米松氏への指導の準備を勧めます</div>
      </div>
    </div>
<% end %>
  </div>

  <div class="chat-footer">

    <% case current_user.progress_level %>
      <% when 12 %>
        <%= form_with url: line_page_child_consultation_path, method: :post, local: true, html: { class: "chat-form" } do %>
          <%= text_field_tag :chat_8, nil, placeholder: "メッセージを入力...", class: "chat-input" %>
          <%= submit_tag "▶", class: "chat-button" %>
        <% end %>
      <% when 13 %>
        <%= form_with url: line_page_child_consultation_path, method: :post, local: true, html: { class: "chat-form" } do %>
          <%= text_field_tag :chat_9, nil, placeholder: "メッセージを入力...", class: "chat-input" %>
          <%= submit_tag "▶", class: "chat-button" %>
        <% end %>
    <% end %>

  </div>
</div>


<style>
body {
background-color: #d3e8d3;
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
margin: 0;
font-family: Arial, sans-serif;
}
.chat-container {
width: 480px;
height: 600px;
background: #fff;
border-radius: 15px;
overflow: hidden;
display: flex;
flex-direction: column;
box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}
.chat-header {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  padding: 10px 0;
  background-color: #06C755;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
}

.chat-header .back-button {
  position: absolute;
  left: 10px;
}

.chat-header .back-button a {
  color: #fff;
  text-decoration: none;
  font-size: 16px;
}

.chat-header .back-icon {
  margin-right: 5px;
}

.chat-header .header-title {
  text-align: center;
}
.chat-body {
flex: 1;
padding: 15px;
overflow-y: auto;
display: flex;
flex-direction: column;
}
.message-container {
display: flex;
align-items: flex-start;
margin-bottom: 10px;
}
.message-container.user {
flex-direction: row-reverse;
}
.message-container img {
width: 40px;
height: 40px;
border-radius: 50%;
margin: 0 10px;
}
.message-content {
max-width: 70%;
}
.username {
font-size: 12px;
color: #888;
margin-bottom: 2px;
}
.message {
padding: 10px;
border-radius: 10px;
}
.message.user {
background: #06C755;
color: white;
border-bottom-right-radius: 0;
}
.message.friend {
background: #f1f1f1;
color: black;
border-bottom-left-radius: 0;
}
.chat-footer {
  display: flex;
  padding: 10px;
  background: #f1f1f1;
}

.chat-form {
  /* フォーム全体を flex 要素として扱ってもOK */
  display: flex;
  width: 100%;
}

.chat-input {
  flex: 1;
  padding: 10px;
  border: none;
  border-radius: 20px;
  outline: none;
}

.chat-button {
  background: #06C755;
  color: white;
  border: none;
  padding: 10px 15px;
  margin-left: 5px;
  border-radius: 50%;
  cursor: pointer;
}
</style>

app/views/line_page/group.html.erb
<% if current_user.progress_level == 2 || current_user.progress_level <= 4 %>
<%= render "line_page/group-chat-list/group-chat-list-1" %>
<% elsif current_user.progress_level <= 8 %>
<%= render "line_page/group-chat-list/group-chat-list-2" %>
<% elsif current_user.progress_level <= 11 %>
<%= render "line_page/group-chat-list/group-chat-list-3" %>
<% elsif current_user.progress_level <= 15 %>
<%= render "line_page/group-chat-list/group-chat-list-4" %>
<% end %>



<style>
body {
background-color: #d3e8d3;
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
margin: 0;
font-family: Arial, sans-serif;
}
.chat-container {
width: 480px;
height: 600px;
background: #fff;
border-radius: 15px;
overflow: hidden;
display: flex;
flex-direction: column;
box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}
.chat-header {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  padding: 10px 0;
  background-color: #06C755;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
}

.chat-header .back-button {
  position: absolute;
  left: 10px;
}

.chat-header .back-button a {
  color: #fff;
  text-decoration: none;
  font-size: 16px;
}

.chat-header .back-icon {
  margin-right: 5px;
}

.chat-header .header-title {
  text-align: center;
}
.chat-body {
flex: 1;
padding: 15px;
overflow-y: auto;
display: flex;
flex-direction: column;
}
.message-container {
display: flex;
align-items: flex-start;
margin-bottom: 10px;
}
.message-container.user {
flex-direction: row-reverse;
}
.message-container img {
width: 40px;
height: 40px;
border-radius: 50%;
margin: 0 10px;
}
.message-content {
max-width: 70%;
}
.username {
font-size: 12px;
color: #888;
margin-bottom: 2px;
}
.message {
padding: 10px;
border-radius: 10px;
}
.message.user {
background: #06C755;
color: white;
border-bottom-right-radius: 0;
}
.message.friend {
background: #f1f1f1;
color: black;
border-bottom-left-radius: 0;
}
.chat-footer {
  display: flex;
  padding: 10px;
  background: #f1f1f1;
}

.chat-form {
  /* フォーム全体を flex 要素として扱ってもOK */
  display: flex;
  width: 100%;
}

.chat-input {
  flex: 1;
  padding: 10px;
  border: none;
  border-radius: 20px;
  outline: none;
}

.chat-button {
  background: #06C755;
  color: white;
  border: none;
  padding: 10px 15px;
  margin-left: 5px;
  border-radius: 50%;
  cursor: pointer;
}
</style>

app/views/line_page/hayato.html.erb
<% if current_user.progress_level >= 1 %>
<%= render "line_page/hayato-chat-list/hayato-chat-list-1" %>
<% end %>


<style>
body {
background-color: #d3e8d3;
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
margin: 0;
font-family: Arial, sans-serif;
}
.chat-container {
width: 480px;
height: 600px;
background: #fff;
border-radius: 15px;
overflow: hidden;
display: flex;
flex-direction: column;
box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}
.chat-header {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  padding: 10px 0;
  background-color: #06C755;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
}

.chat-header .back-button {
  position: absolute;
  left: 10px;
}

.chat-header .back-button a {
  color: #fff;
  text-decoration: none;
  font-size: 16px;
}

.chat-header .back-icon {
  margin-right: 5px;
}

.chat-header .header-title {
  text-align: center;
}
.chat-body {
flex: 1;
padding: 15px;
overflow-y: auto;
display: flex;
flex-direction: column;
}
.message-container {
display: flex;
align-items: flex-start;
margin-bottom: 10px;
}
.message-container.user {
flex-direction: row-reverse;
}
.message-container img {
width: 40px;
height: 40px;
border-radius: 50%;
margin: 0 10px;
}
.message-content {
max-width: 70%;
}
.username {
font-size: 12px;
color: #888;
margin-bottom: 2px;
}
.message {
padding: 10px;
border-radius: 10px;
}
.message.user {
background: #06C755;
color: white;
border-bottom-right-radius: 0;
}
.message.friend {
background: #f1f1f1;
color: black;
border-bottom-left-radius: 0;
}
.chat-footer {
  display: flex;
  padding: 10px;
  background: #f1f1f1;
}

.chat-form {
  /* フォーム全体を flex 要素として扱ってもOK */
  display: flex;
  width: 100%;
}

.chat-input {
  flex: 1;
  padding: 10px;
  border: none;
  border-radius: 20px;
  outline: none;
}

.chat-button {
  background: #06C755;
  color: white;
  border: none;
  padding: 10px 15px;
  margin-left: 5px;
  border-radius: 50%;
  cursor: pointer;
}
</style>

app/views/line_page/keisuke.html.erb
<% if current_user.progress_level >= 1 %>
<%= render "line_page/keisuke-chat-list/keisuke-chat-list-1" %>
<% end %>



<style>
body {
background-color: #d3e8d3;
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
margin: 0;
font-family: Arial, sans-serif;
}
.chat-container {
width: 480px;
height: 600px;
background: #fff;
border-radius: 15px;
overflow: hidden;
display: flex;
flex-direction: column;
box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}
.chat-header {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  padding: 10px 0;
  background-color: #06C755;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
}

.chat-header .back-button {
  position: absolute;
  left: 10px;
}

.chat-header .back-button a {
  color: #fff;
  text-decoration: none;
  font-size: 16px;
}

.chat-header .back-icon {
  margin-right: 5px;
}

.chat-header .header-title {
  text-align: center;
}
.chat-body {
flex: 1;
padding: 15px;
overflow-y: auto;
display: flex;
flex-direction: column;
}
.message-container {
display: flex;
align-items: flex-start;
margin-bottom: 10px;
}
.message-container.user {
flex-direction: row-reverse;
}
.message-container img {
width: 40px;
height: 40px;
border-radius: 50%;
margin: 0 10px;
}
.message-content {
max-width: 70%;
}
.username {
font-size: 12px;
color: #888;
margin-bottom: 2px;
}
.message {
padding: 10px;
border-radius: 10px;
}
.message.user {
background: #06C755;
color: white;
border-bottom-right-radius: 0;
}
.message.friend {
background: #f1f1f1;
color: black;
border-bottom-left-radius: 0;
}
.chat-footer {
  display: flex;
  padding: 10px;
  background: #f1f1f1;
}

.chat-form {
  /* フォーム全体を flex 要素として扱ってもOK */
  display: flex;
  width: 100%;
}

.chat-input {
  flex: 1;
  padding: 10px;
  border: none;
  border-radius: 20px;
  outline: none;
}

.chat-button {
  background: #06C755;
  color: white;
  border: none;
  padding: 10px 15px;
  margin-left: 5px;
  border-radius: 50%;
  cursor: pointer;
}
</style>

app/views/line_page/top.html.erb
<div class="chat-container">
<header class="top-bar">

<h1>トーク一覧</h1>
<div class="icons">
    <span>🔍</span>
    <span>📂</span>
    <span>⚙</span>
</div>
</header>

<div class="search-bar">
<input type="text" placeholder="🔍 検索（使用できません）">
</div>



<main class="chat-list">

<% if current_user.progress_level <= 4 %>
<%= render "line_page/chat-list/chat-list-1" %>
<% elsif current_user.progress_level <= 8 %>
<%= render "line_page/chat-list/chat-list-2" %>
<% elsif current_user.progress_level <= 11 %>
<%= render "line_page/chat-list/chat-list-3" %>
<% elsif current_user.progress_level <= 15 %>
<%= render "line_page/chat-list/chat-list-4" %>
<% end %>


<% if current_user.progress_level >= 5 %>
    <%= link_to line_page_history_path, style: "text-decoration:none; color:inherit;" do %>
    <div class="chat-item">
      <img src="/assets/history.png" alt="ユーザー">
        <div class="chat-info">
            <h2>グループチャットの履歴</h2>

        </div>
        
    </div>
    <% end %>
<% end %>



</main>

</div>

<div class="dash text-center mt-3 mb-3">
<%= link_to 'ダッシュボードへ', home_dashboard_path, class: 'btn btn-primary' %>
</div>

<style>
body {
  background-color: #d3e8d3;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: 0;
  font-family: Arial, sans-serif;
}

.chat-container {
  width: 480px;
  height: 600px;
  background: #fff;
  border-radius: 15px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
  position: relative;
}

.top-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  background-color: white;
  border-bottom: 2px solid #f0f0f0;
}

/* ヘッダー内の時刻 */
.top-bar .time {
  font-size: 16px;
}

.icons span {
  margin: 0 8px;
  cursor: pointer;
}

.search-bar {
  padding: 10px;
  background-color: white;
}

.search-bar input {
  width: 100%;
  padding: 8px;
  border-radius: 8px;
  border: 1px solid #ddd;
}


.chat-list {
  padding: 10px;
}

.chat-item {
  display: flex;
  align-items: center;
  background: white;
  margin-bottom: 8px;
  padding: 10px;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  position: relative;
}

.chat-item img {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  margin-right: 10px;
}

.chat-info {
  flex: 1;
}

.chat-info h2 {
  font-size: 16px;
  margin: 0;
}

.chat-info p {
  font-size: 12px;
  color: gray;
  margin: 2px 0 0;
}

/* チャット項目内の時刻 */
.chat-item .time {
  font-size: 12px;
  color: gray;
  margin-left: 10px;
}

.badge {
  background: orange;
  color: white;
  font-size: 12px;
  padding: 5px 8px;
  border-radius: 50%;
  position: absolute;
  right: 10px;
  top: 10px;
}

.dash{
  position: absolute;
  bottom: 0;
  
}

</style>